config log fortianalyzer setting
  set status enable
  set server 10.10.30.20
  set upload-option realtime
  set reliable enable
end
config log setting
  set local-in-allow enable
  set local-in-deny-broadcast disable
end
# Make sure each policy has: set logtraffic all
